jobs:
- job: Windows_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      stack-8.8.2:
        YAML_FILE: stack-8.8.2.yaml
      stack-8.8.1:
        YAML_FILE: stack-8.8.1.yaml
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
      stack-8.2.2:
        YAML_FILE: stack-8.2.2.yaml
  variables:
    STACK_ROOT: "C:\\sr"

  steps:
  - task: Cache@2
    inputs:
      key: '"stack" | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(YAML_FILE)'
      path: .azure-cache
      cacheHitVar: CACHE_RESTORED
    displayName: "Cache stack-root"
  - bash: |
      mkdir -p $STACK_ROOT
      tar -vxzf .azure-cache/stack-root.tar.gz -C /c
      mkdir -p .stack-work
      tar -vxzf .azure-cache/stack-work.tar.gz
    displayName: "Unpack cache"
    condition: eq(variables.CACHE_RESTORED, 'true')
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      mkdir -p "$STACK_ROOT"
    displayName: Install stack
  - bash: |
      source .azure/windows-stack.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows-stack.bashrc
      stack build --stack-yaml $(YAML_FILE) --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/windows-stack.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `haskell-lsp`
  - bash: |
      source .azure/windows-stack.bashrc
      stack build --stack-yaml $(YAML_FILE) --flag haskell-lsp:demo
    displayName: Build language server example
  - bash: |
      source .azure/windows-stack.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
    displayName: Build Test-dependencies
  - bash: |
      source .azure/windows-stack.bashrc
      stack test --stack-yaml $(YAML_FILE) --dump-logs
    displayName: "Run Tests"
  - bash: |
      mkdir -p .azure-cache
      tar -vczf .azure-cache/stack-root.tar.gz $(cygpath $STACK_ROOT)
      tar -vczf .azure-cache/stack-work.tar.gz .stack-work
    displayName: "Pack cache"
